# -*- ruby -*-

source "http://api.berkshelf.com/"

cookbook "groonga", :git => "https://github.com/groonga/chef-cookbooks.git", :rel => "groonga"
cookbook "droonga", :git => "https://github.com/droonga/chef-cookbooks.git", :rel => "droonga"
